In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

   Data read
        |
   Data Cleaning
       |
   Data Analysis
       |
   Feature Engineering
       |
   Feature Selection
       |
    Model development
       |
   Model Evalution
       |
    Model Turning
       |
    Model deployment

**Feature Engineering**

- So far we have perfromed feature analysis

    - Data frame quick checks
 
    - Categorical coloumn analysis
 
    - Bar chart, pie charts
 
    - Numerical column analysis
 
    - Histogram, Box plot, Outlier
 
    - Bi-multi vaiate analysis
 
    - correlation etc
 
- Now we need to lerann Feature enfineering

    - we will create a new column
 
    - we will perfrom the **Encoding**,Which is convert categorical to numerical  data
 
    - we will do **Transfformation**
 
    - we will perfrom **Scalling: Standerdization and Normalization**
 
    - we will perfrrom  the **missing value analysis**
 
- simply feature engineering means our data is modified

In [2]:
visa_df=pd.read_csv(r"C:\Users\Patel\Documents\NareshIt\EDA\Visadataset.csv")
visa_df
num=visa_df.select_dtypes(include='object').columns
cat=visa_df.select_dtypes(exclude='object').columns
num,cat

(Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

**case status**

In [12]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

In [4]:
d={'Certified':0,'Denied':1}

In [5]:
# map the above the dictionary with original column
visa_df['case_status']=visa_df['case_status'].map(d)

In [6]:
visa_df['education_of_employee'].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [25]:
labels=sorted(visa_df['education_of_employee'].unique())
d={j:i for i,j in enumerate(labels)}
visa_df['education_of_employee'].map(d)

0        2
1        3
2        0
3        0
4        3
        ..
25475    0
25476    2
25477    3
25478    3
25479    0
Name: education_of_employee, Length: 25480, dtype: int64

In [26]:
d

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

- there are two encodings

    - LabelEncoder

    - OrdinalEncoder

- sklearn: **Package**

    - preprocessing: **module**

        - LabelEncoder: **class**

            - fit_transform:**method** 

import sklearn
skleran.preprocessing

from sklearn import preprocessing
dir(preprocessing): LabelEncoder
preprocessing.LabelEncoder

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform()

# Read the class
# save the class
# apply the fit transform

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
oe.fit_transform

**fit transform**

- fit : created a dictionary(find something)

- transform: using above finding we are modify the data


from sklearn.module import class

va=class()

va.fit   or va.fit_transform

Education  LabelEncoder  OrdinalEncoder
=======================================
HighSchool     1              0

Bachelor       0              1

Masters        2              2 

PHD            3               3

1  0    2  3===>

In [27]:
visa_df=pd.read_csv(r"C:\Users\Patel\Documents\NareshIt\EDA\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

- sklearn  :**Package**

    - prepeocessing: **module**

              - LabelEncoder:**class**

              - Fit transfrom : **Method**

import sklearn
sklearns.preprocessing

**fit transfrom**

- fit: created a dictionary (find somethig)

- Transfrom : using above finding we are modify the data

- sklearn

**LabelEncoder**

In [5]:
visa_df=pd.read_csv(r"C:\Users\Patel\Documents\NareshIt\EDA\Visadataset.csv")
visa_df
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(visa_df['case_status'])

array([1, 0, 1, ..., 0, 0, 0], shape=(25480,))

In [8]:
visa_df=pd.read_csv(r"C:\Users\Patel\Documents\NareshIt\EDA\Visadataset.csv")
cat=visa_df.select_dtypes(exclude='object').columns

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cat=visa_df.select_dtypes(exclude='object').columns
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])

In [13]:
visa_df

         case_id continent education_of_employee  ... unit_of_wage full_time_position  case_status
0         EZYV01      Asia           High School  ...         Hour                  Y       Denied
1         EZYV02      Asia              Master's  ...         Year                  Y    Certified
2         EZYV03      Asia            Bachelor's  ...         Year                  Y       Denied
3         EZYV04      Asia            Bachelor's  ...         Year                  Y       Denied
4         EZYV05    Africa              Master's  ...         Year                  Y    Certified
...          ...       ...                   ...  ...          ...                ...          ...
25475  EZYV25476      Asia            Bachelor's  ...         Year                  Y    Certified
25476  EZYV25477      Asia           High School  ...         Year                  Y    Certified
25477  EZYV25478      Asia              Master's  ...         Year                  N    Certified
25478  EZYV25479      Asia              Master's  ...         Year                  Y    Certified
25479  EZYV25480      Asia            Bachelor's  ...         Year                  Y    Certified

[25480 rows x 12 columns]

In [15]:
visa_df=pd.read_csv(r"C:\Users\Patel\Documents\NareshIt\EDA\Visadataset.csv")

In [22]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
cat=visa_df.select_dtypes(include='string').columns
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[[i]])

In [23]:
visa_df

         case_id continent education_of_employee  ... unit_of_wage full_time_position  case_status
0         EZYV01      Asia           High School  ...         Hour                  Y       Denied
1         EZYV02      Asia              Master's  ...         Year                  Y    Certified
2         EZYV03      Asia            Bachelor's  ...         Year                  Y       Denied
3         EZYV04      Asia            Bachelor's  ...         Year                  Y       Denied
4         EZYV05    Africa              Master's  ...         Year                  Y    Certified
...          ...       ...                   ...  ...          ...                ...          ...
25475  EZYV25476      Asia            Bachelor's  ...         Year                  Y    Certified
25476  EZYV25477      Asia           High School  ...         Year                  Y    Certified
25477  EZYV25478      Asia              Master's  ...         Year                  N    Certified
25478  EZYV25479      Asia              Master's  ...         Year                  Y    Certified
25479  EZYV25480      Asia            Bachelor's  ...         Year                  Y    Certified

[25480 rows x 12 columns]

In [24]:
visa_df=pd.read_csv(r"C:\Users\Patel\Documents\NareshIt\EDA\Visadataset.csv")

**pd.get_dummies**

- get dummies is a way to represent the categorical columns to numerical

- first it will check what ate the labels in a column

- for example  casse statuss has ttwo labels 

    - Denied and certified
- so it  will create two new columns based on labels 

    - col1: case_status_denied
    - col2:case_status_certified

case_status| case_status_denied|case_status_certified
-          | -                 |-
Denied     | 1                 | 0
Certified  | 0                 | 1
Certified  | 0                 | 1

**It is also called as One Hot Encoder**
- It makes new columns are independent each other

- Some of ML algorithm expect that column should be independent each other

In [25]:
pd.get_dummies(visa_df['case_status'],
               dtype=int
              )

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]