**How to create a Null values in a data**

- None
- np.nan

In [2]:
import numpy as np
import pandas as pd

In [3]:
d={'Names':['Ramesh','Suresh',None,'Mahesh'],
  'Age':[None,22,23,25],
  'City':['hyd','blr','pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   hyd
1  Suresh  22.0   blr
2    None  23.0  pune
3  Mahesh  25.0  None

In [4]:
df1.to_csv('data1.csv',index=False)

In [5]:
d={'Names':['Ramesh','Suresh',np.nan,'Mahesh'],
  'Age':[np.nan,22,23,25],
  'City':['hyd','blr','pune',np.nan]}
df2=pd.DataFrame(d)
df2.to_csv('data2.csv',index=False)

- Categorical data use **None**

- Numerical data use **np.nan**

In [6]:
np.nan+10

nan

In [7]:
None+10

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [8]:
df1.isnull()
# isnull = whereever Null value is there it dispaly as true

   Names    Age   City
0  False   True  False
1  False  False  False
2   True  False  False
3  False  False   True

In [9]:
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

In [10]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**fill the values**

In [11]:
# Random filling
df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   hyd
1  Suresh  22.0   blr
2      30  23.0  pune
3  Mahesh  25.0    30

In [12]:
# Select one column and will with value
df1['City'].fillna('Delhi')

0      hyd
1      blr
2     pune
3    Delhi
Name: City, dtype: object

In [13]:
df1.fillna(method='pad')

C:\Users\Patel\AppData\Local\Temp\ipykernel_15624\3887010614.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN   hyd
1  Suresh  22.0   blr
2  Suresh  23.0  pune
3  Mahesh  25.0  pune

In [14]:
df1.fillna(method='pad',axis=1)

C:\Users\Patel\AppData\Local\Temp\ipykernel_15624\1258234312.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   hyd
1  Suresh    22.0   blr
2    None    23.0  pune
3  Mahesh    25.0  25.0

In [15]:
df1.fillna(method='bfill')

C:\Users\Patel\AppData\Local\Temp\ipykernel_15624\2949398996.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')

    Names   Age  City
0  Ramesh  22.0   hyd
1  Suresh  22.0   blr
2  Mahesh  23.0  pune
3  Mahesh  25.0  None

In [16]:
df1.fillna(method='bfill',axis=1)

C:\Users\Patel\AppData\Local\Temp\ipykernel_15624\2900121331.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

    Names   Age  City
0  Ramesh   hyd   hyd
1  Suresh  22.0   blr
2    23.0  23.0  pune
3  Mahesh  25.0  None

- mean 

- median 

- mode

In [17]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.333333
1    22.000000
2    23.000000
3    25.000000
Name: Age, dtype: float64

In [18]:
age_mode=df1['Age'].mode()
df1['Age'].fillna(age_mode)

0    22.0
1    22.0
2    23.0
3    25.0
Name: Age, dtype: float64

In [19]:
age_median=df1['Age'].median()
df1['Age'].fillna(age_median)

0    23.0
1    22.0
2    23.0
3    25.0
Name: Age, dtype: float64

In [20]:
# there is no perticular rule how to fill the missing values
# IT completely based on situation

In [21]:
age_mean=df1

In [22]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [36]:
d1 # I want to handover this data to my students with not encode

   Gender
0    Male
1  Female
2    None

In [37]:
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     NaN
1     NaN
2     NaN

In [38]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])
d={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

   Gender
0     1.0
1     0.0
2     NaN

**Situation-2**

In [29]:
# ML algorithm
# chrun : stay or not stay
chrun=['stay','not_stay',None]
chrun=[0,1,None]
chrun=[0,1,0.5]

**Situation-3**

In [30]:
#NO of days
[20,25,np.nan,31]
(25+20+31)/3

25.333333333333332

**Situation-4**

In [39]:
course=['DS','AI','DS','Devops','AI','Devlops','AI']
fee=[30000,2700,30000,22000,3000,22000,np.nan]
pd.DataFrame(zip(course,fee))

# First group by with  course
# then take corresponding course values only

         0        1
0       DS  30000.0
1       AI   2700.0
2       DS  30000.0
3   Devops  22000.0
4       AI   3000.0
5  Devlops  22000.0
6       AI      NaN

**KNNImputer**

- KNN : K-nearnest neighbours

- where K iis number

- instead of taking avg of all the value  data

    - first will find the neighbourd who are close with missing data

    - by using Euclidian distance calculation will identify the neighbour rows

    - suppose k=2 will identify the two closet rows 

    - finally will with mean

In [32]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),
               columns=["Salary","Age"])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn 

    - impute

        - KNNimputer

In [33]:
from sklearn.impute import KNNImputer
imputer=KNNImputer(n_neighbors=2)
pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0

In [41]:
6.0e+04

60000.0